theme = "hugo_theme_beg"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ron Brown"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/brownrv/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/brownrv"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ronvbrown"